// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompteService.proto

package ma.grpc.project.stubs;

public interface DeleteCompteByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteCompteByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * L'ID du compte à supprimer
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * L'ID du compte à supprimer
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
