// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompteService.proto

package ma.grpc.project.stubs;

public interface FindByTypeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FindByTypeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Type de compte à filtrer
   * </pre>
   *
   * <code>.TypeCompte type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   * Type de compte à filtrer
   * </pre>
   *
   * <code>.TypeCompte type = 1;</code>
   * @return The type.
   */
  TypeCompte getType();
}
